version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestIssueScafoldingProject
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.testissuescafolding.integrations:test1X
  packages:
  - name: TestIssueScafoldingProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2058
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.1.0.0.2058
- serviceName: project.testissuescafolding.integrations:test1X1
  packages:
  - name: TestIssueScafoldingProject
    version: "1.0"
- serviceName: project.testissuescafolding.referencedata:TesRefData
  packages:
  - name: TestIssueScafoldingProject
    version: "1.0"
